// Auto-generated by tools/split_engine.py from engine.cu.
// Edit this file directly; engine.cu just #includes us.

#pragma once

__global__ void aft_full_fwd(float *Q, float *K, float *V, float *WB, float *out,
                             int T, int D, bool masked)
{
    int t = blockIdx.x * blockDim.x + threadIdx.x;
    if (t < T)
    {
        for (int d = 0; d < D; d++)
        {
            int limit = masked ? (t + 1) : T;

            // --- Phase 1: Find Max for Numerical Stability ---
            float max_val = -1e20f;
            for (int tp = 0; tp < limit; tp++)
            {
                float val = K[tp * D + d] + WB[t * T + tp];
                if (val > max_val)
                    max_val = val;
            }

            // --- Phase 2: Compute Stable Weighted Sum ---
            float numerator = 0.0f;
            float denominator = 0.0f;
            for (int tp = 0; tp < limit; tp++)
            {
                // exp(val - max_val) is always <= 1.0f
                float exp_weight = expf(K[tp * D + d] + WB[t * T + tp] - max_val);
                numerator += exp_weight * V[tp * D + d];
                denominator += exp_weight;
            }

            float sigQ = 1.0f / (1.0f + expf(-Q[t * D + d]));
            out[t * D + d] = sigQ * (numerator / (denominator + 1e-6f));
        }
    }
}
__global__ void aft_cross_fwd(float *Q, float *K, float *V, float *WB, float *out,
                              int TDec, int TEnc, int D)
{
    int t = blockIdx.x * blockDim.x + threadIdx.x;
    if (t < TDec)
    {
        for (int d = 0; d < D; d++)
        {
            // Find Max
            float max_val = -1e20f;
            for (int tp = 0; tp < TEnc; tp++)
            {
                float val = K[tp * D + d] + WB[t * TEnc + tp];
                if (val > max_val)
                    max_val = val;
            }

            float numerator = 0.0f;
            float denominator = 0.0f;
            for (int tp = 0; tp < TEnc; tp++)
            {
                float exp_weight = expf(K[tp * D + d] + WB[t * TEnc + tp] - max_val);
                numerator += exp_weight * V[tp * D + d];
                denominator += exp_weight;
            }

            float sigQ = 1.0f / (1.0f + expf(-Q[t * D + d]));
            out[t * D + d] = sigQ * (numerator / (denominator + 1e-6f));
        }
    }
}
__global__ void aft_cross_bwd(
    float *Q, float *K, float *V, float *WB,
    float *grad_out,
    float *grad_Q, float *grad_K, float *grad_V, float *grad_WB,
    int TDec, int TEnc, int D)
{
    int t = blockIdx.x * blockDim.x + threadIdx.x;
    if (t >= TDec)
        return;

    for (int d = 0; d < D; d++)
    {
        // --- 1. Re-calculate Stable Forward Components ---
        float max_val = -1e20f;
        for (int tp = 0; tp < TEnc; tp++)
        {
            float v = K[tp * D + d] + WB[t * TEnc + tp];
            if (v > max_val)
                max_val = v;
        }

        float num = 0.0f;
        float den = 0.0f;
        for (int tp = 0; tp < TEnc; tp++)
        {
            float weight = expf(K[tp * D + d] + WB[t * TEnc + tp] - max_val);
            num += weight * V[tp * D + d];
            den += weight;
        }

        float den_inv = 1.0f / (den + 1e-6f);
        float ratio = num * den_inv;
        float sigQ = 1.0f / (1.0f + expf(-Q[t * D + d]));
        float gO = grad_out[t * D + d];

        // --- 2. Compute Gradients ---
        // Gradient for Q (Sigmoid derivative)
        float dQ = gO * ratio * sigQ * (1.0f - sigQ);
        atomicAdd(&grad_Q[t * D + d], dQ);

        for (int tp = 0; tp < TEnc; tp++)
        {
            float weight = expf(K[tp * D + d] + WB[t * TEnc + tp] - max_val);

            // dL/dV
            float dV = gO * sigQ * (weight * den_inv);
            atomicAdd(&grad_V[tp * D + d], dV);

            // dL/dK and dL/dWB
            // The derivative of (num/den) w.r.t the exponent (K+W) is weight * (V - ratio) / den
            float dW = gO * sigQ * weight * (V[tp * D + d] - ratio) * den_inv;

            atomicAdd(&grad_K[tp * D + d], dW);
            atomicAdd(&grad_WB[t * TEnc + tp], dW);
        }
    }
}
__global__ void concat_axis1_fwd(float **inputs, float *out, int num_tensors, int rows, int cols_per_tensor)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    int total_cols = num_tensors * cols_per_tensor;
    int size = rows * total_cols;

    if (i < size)
    {
        int r = i / total_cols;
        int c = i % total_cols;
        int tensor_idx = c / cols_per_tensor;
        int local_c = c % cols_per_tensor;

        out[i] = inputs[tensor_idx][r * cols_per_tensor + local_c];
    }
}

// Axis-0 concat: copies each input row-block sequentially.
// Inputs are [rows_i, cols] all sharing the same `cols`.
// `row_offsets` has length num_tensors + 1; row_offsets[k] = sum(rows_0..rows_{k-1}),
// row_offsets[num_tensors] = total_rows.
__global__ void concat_axis0_fwd(float **inputs, float *out, int num_tensors,
                                 const int *row_offsets, int cols)
{
    int total_rows = row_offsets[num_tensors];
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    int size = total_rows * cols;
    if (i >= size) return;

    int r = i / cols;
    int c = i % cols;

    // Find which input row r belongs to (linear scan; num_tensors is small).
    int t = 0;
    while (t + 1 < num_tensors && r >= row_offsets[t + 1]) t++;
    int local_r = r - row_offsets[t];
    out[i] = inputs[t][local_r * cols + c];
}

__global__ void concat_axis0_bwd(float *grad_out, float **grad_inputs, int num_tensors,
                                 const int *row_offsets, int cols)
{
    int total_rows = row_offsets[num_tensors];
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    int size = total_rows * cols;
    if (i >= size) return;

    int r = i / cols;
    int c = i % cols;

    int t = 0;
    while (t + 1 < num_tensors && r >= row_offsets[t + 1]) t++;
    int local_r = r - row_offsets[t];
    atomicAdd(&grad_inputs[t][local_r * cols + c], grad_out[i]);
}

__global__ void concat_axis1_bwd(float *grad_out, float **grad_inputs, int num_tensors, int rows, int cols_per_tensor)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    int total_cols = num_tensors * cols_per_tensor;
    int size = rows * total_cols;

    if (i < size)
    {
        int r = i / total_cols;
        int c = i % total_cols;
        int tensor_idx = c / cols_per_tensor;
        int local_c = c % cols_per_tensor;

        atomicAdd(&grad_inputs[tensor_idx][r * cols_per_tensor + local_c], grad_out[i]);
    }
}

