// Auto-generated by tools/split_engine.py from engine.cu.
// Edit this file directly; engine.cu just #includes us.

#pragma once

#include <cuda_runtime.h>
#include <cstdio>
#include <vector>
#include <unordered_set>
#include <unordered_map>
#include <functional>
#include <memory>
#include <mutex>
#include <cmath>
#include <curand_kernel.h>
#include <cooperative_groups.h>
#include <cooperative_groups/reduce.h>

#define DLLEXPORT __attribute__((visibility("default")))

namespace cg = cooperative_groups;

// __global__ void l2_normalize_fwd(float *a, float *out, int R, int C, float eps)
// {
//     int i = blockIdx.x * blockDim.x + threadIdx.x;
//     if (i < R)
//     {
//         float sum_sq = 0.0f;
//         for (int j = 0; j < C; j++)
//         {
//             float val = a[i * C + j];
//             sum_sq += val * val;
//         }
//         float norm = sqrtf(sum_sq + eps);
//         for (int j = 0; j < C; j++)
//         {
//             out[i * C + j] = a[i * C + j] / norm;
//         }
//     }
// }

// __global__ void l2_normalize_bwd(float *a, float *go, float *ga, int R, int C, float eps)
// {
//     int i = blockIdx.x * blockDim.x + threadIdx.x;
//     if (i < R)
//     {
//         float sum_sq = 0.0f;
//         for (int j = 0; j < C; j++)
//         {
//             float val = a[i * C + j];
//             sum_sq += val * val;
//         }
//         float norm_sq = sum_sq + eps;
//         float norm = sqrtf(norm_sq);
//         float norm_cubed = norm_sq * norm;

//         float dot_product = 0.0f;
//         for (int j = 0; j < C; j++)
//         {
//             dot_product += a[i * C + j] * go[i * C + j];
//         }

//         for (int j = 0; j < C; j++)
//         {
//             // Formula: (grad_out / norm) - (a * dot_product / norm^3)
//             float grad = (go[i * C + j] / norm) - (a[i * C + j] * dot_product / norm_cubed);
//             atomicAdd(&ga[i * C + j], grad);
//         }
//     }
// }
