// Auto-generated by tools/split_engine.py from engine.cu.
// Edit this file directly; engine.cu just #includes us.

#pragma once

__global__ void slice_fwd_kernel(float *full_data, float *slice_data, int start_idx, int total_elements)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < total_elements)
    {
        slice_data[i] = full_data[start_idx + i];
    }
}

__global__ void slice_bwd_kernel(float *full_grad, float *slice_grad, int start_idx, int total_elements)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < total_elements)
    {
        // Use atomicAdd because multiple slices could overlap the same memory
        atomicAdd(&full_grad[start_idx + i], slice_grad[i]);
    }
}

__global__ void compute_cost_matrix_kernel(
    float *pred_boxes,  // [num_queries * 4]
    float *gt_boxes,    // [num_gt * 4]
    float *cost_matrix, // [num_queries * num_gt]
    int num_queries,
    int num_gt)
{
    int q = blockIdx.y * blockDim.y + threadIdx.y; // Query index
    int g = blockIdx.x * blockDim.x + threadIdx.x; // GT index

    if (q < num_queries && g < num_gt)
    {
        float l1_loss = 0.0f;
        for (int i = 0; i < 4; i++)
        {
            l1_loss += fabsf(pred_boxes[q * 4 + i] - gt_boxes[g * 4 + i]);
        }
        cost_matrix[q * num_gt + g] = l1_loss;
    }
}

// --- Reduction Kernels ---

__global__ void xavier_init_kernel(float *data, int size, int n_in, int n_out, unsigned long seed)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < size)
    {
        curandState state;
        // Seed + i ensures every single weight gets a different random number
        curand_init(seed, i, 0, &state);

        float limit = sqrtf(6.0f / (float)(n_in + n_out));
        // curand_uniform is [0,1], we transform to [-limit, limit]
        data[i] = (curand_uniform(&state) * 2.0f - 1.0f) * limit;
    }
}

__global__ void im2col_kernel(const float *data_im, const int channels,
                              const int height, const int width, const int kernel_h, const int kernel_w,
                              const int pad_h, const int pad_w, const int stride_h, const int stride_w,
                              const int height_col, const int width_col, float *data_col)
{

    int index = blockIdx.x * blockDim.x + threadIdx.x;
    int num_outputs = height_col * width_col;
    int total_threads = channels * num_outputs;

    if (index < total_threads)
    {
        // Map thread to a specific output spatial location
        int w_out = index % width_col;
        int h_out = (index / width_col) % height_col;
        int c_im = index / num_outputs;

        int h_in_start = h_out * stride_h - pad_h;
        int w_in_start = w_out * stride_w - pad_w;

        // The column in the ColBuffer [PatchSize x NumOutputs]
        int col = h_out * width_col + w_out;

        for (int i = 0; i < kernel_h; ++i)
        {
            for (int j = 0; j < kernel_w; ++j)
            {
                // 'row' is which element of the 9-element patch we are filling
                int row = (c_im * kernel_h * kernel_w) + (i * kernel_w + j);

                // target_idx must match the MatMul inner-loop K
                // MatMul(A, B) where B is colBuffer.
                // B is accessed as B[i * N + col].
                // Here 'i' is 'row' and 'N' is 'num_outputs'.
                int target_idx = row * num_outputs + col;

                int r = h_in_start + i;
                int c = w_in_start + j;

                if (r >= 0 && r < height && c >= 0 && c < width)
                {
                    data_col[target_idx] = data_im[(c_im * height + r) * width + c];
                }
                else
                {
                    data_col[target_idx] = 0.0f;
                }
            }
        }
    }
}
// --- Backward Pass Utility ---
__global__ void col2im_kernel(const float *data_col, const int channels,
                              const int height, const int width, const int kernel_h, const int kernel_w,
                              const int pad_h, const int pad_w, const int stride_h, const int stride_w,
                              const int height_col, const int width_col, float *data_im)
{
    int index = blockIdx.x * blockDim.x + threadIdx.x;
    if (index < channels * height * width)
    {
        float val = 0;
        int w = index % width + pad_w;
        int h = (index / width) % height + pad_h;
        int c = index / (width * height);
        // Compute the range of output pixels that this input pixel contributed to
        for (int kh = 0; kh < kernel_h; ++kh)
        {
            for (int kw = 0; kw < kernel_w; ++kw)
            {
                int h_out = (h - kh);
                int w_out = (w - kw);
                if (h_out % stride_h == 0 && w_out % stride_w == 0)
                {
                    h_out /= stride_h;
                    w_out /= stride_w;
                    if (h_out >= 0 && h_out < height_col && w_out >= 0 && w_out < width_col)
                    {
                        int col_index = (((c * kernel_h + kh) * kernel_w + kw) * height_col + h_out) * width_col + w_out;
                        val += data_col[col_index];
                    }
                }
            }
        }
        data_im[index] = val;
    }
}

