// Auto-generated by tools/split_engine.py from engine.cu.
// Edit this file directly; engine.cu just #includes us.

#pragma once


__global__ void add_fwd(float *a, float *b, float *out, int n)
{
    int i = (blockIdx.x * blockDim.x + threadIdx.x) * 4;
    if (i + 3 < n)
    {
        float4 va = reinterpret_cast<float4 *>(a)[i / 4];
        float4 vb = reinterpret_cast<float4 *>(b)[i / 4];
        float4 vout;
        vout.x = va.x + vb.x;
        vout.y = va.y + vb.y;
        vout.z = va.z + vb.z;
        vout.w = va.w + vb.w;
        reinterpret_cast<float4 *>(out)[i / 4] = vout;
    }
    else
    {
        // Handle remainder
        for (int j = i; j < n; j++)
        {
            out[j] = a[j] + b[j];
        }
    }
}

__global__ void add_bwd(float *go, float *ga, float *gb, int n)
{
    int i = (blockIdx.x * blockDim.x + threadIdx.x) * 4;
    if (i + 3 < n)
    {
        float4 vgo = reinterpret_cast<float4 *>(go)[i / 4];

        // Addition gradient is just passing the output gradient back.
        // Direct addition is safe here because each index is unique to this thread.
        ga[i + 0] += vgo.x;
        ga[i + 1] += vgo.y;
        ga[i + 2] += vgo.z;
        ga[i + 3] += vgo.w;

        gb[i + 0] += vgo.x;
        gb[i + 1] += vgo.y;
        gb[i + 2] += vgo.z;
        gb[i + 3] += vgo.w;
    }
    else
    {
        for (int j = i; j < n; j++)
        {
            ga[j] += go[j];
            gb[j] += go[j];
        }
    }
}
__global__ void sub_fwd(float *a, float *b, float *out, int n)
{
    // Each thread handles 4 elements
    int i = (blockIdx.x * blockDim.x + threadIdx.x) * 4;

    if (i + 3 < n)
    {
        float4 va = reinterpret_cast<float4 *>(a + i)[0];
        float4 vb = reinterpret_cast<float4 *>(b + i)[0];
        float4 res;
        res.x = va.x - vb.x;
        res.y = va.y - vb.y;
        res.z = va.z - vb.z;
        res.w = va.w - vb.w;
        reinterpret_cast<float4 *>(out + i)[0] = res;
    }
    else
    {
        // Handle remainder elements
        for (int j = i; j < n; j++)
        {
            out[j] = a[j] - b[j];
        }
    }
}

__global__ void sub_bwd(float *go, float *ga, float *gb, int n)
{
    int i = (blockIdx.x * blockDim.x + threadIdx.x) * 4;

    if (i + 3 < n)
    {
        float4 vgo = reinterpret_cast<float4 *>(go + i)[0];

        // Note: We use atomicAdd because a tensor might be used
        // in multiple operations (aliasing), requiring gradient accumulation.
        atomicAdd(&ga[i + 0], vgo.x);
        atomicAdd(&ga[i + 1], vgo.y);
        atomicAdd(&ga[i + 2], vgo.z);
        atomicAdd(&ga[i + 3], vgo.w);

        atomicAdd(&gb[i + 0], -vgo.x);
        atomicAdd(&gb[i + 1], -vgo.y);
        atomicAdd(&gb[i + 2], -vgo.z);
        atomicAdd(&gb[i + 3], -vgo.w);
    }
    else
    {
        for (int j = i; j < n; j++)
        {
            atomicAdd(&ga[j], go[j]);
            atomicAdd(&gb[j], -go[j]);
        }
    }
}
__global__ void mul_fwd(float *a, float *b, float *out, int n)
{
    int i = (blockIdx.x * blockDim.x + threadIdx.x) * 4;
    if (i + 3 < n)
    {
        // Vectorized load and store
        float4 va = reinterpret_cast<float4 *>(a)[i / 4];
        float4 vb = reinterpret_cast<float4 *>(b)[i / 4];
        float4 vout;
        vout.x = va.x * vb.x;
        vout.y = va.y * vb.y;
        vout.z = va.z * vb.z;
        vout.w = va.w * vb.w;
        reinterpret_cast<float4 *>(out)[i / 4] = vout;
    }
    else
    {
        // Handle remainder for non-multiple of 4
        for (int j = i; j < n; j++)
        {
            out[j] = a[j] * b[j];
        }
    }
}

__global__ void mul_bwd(float *da, float *db, float *go, float *ga, float *gb, int n)
{
    int i = (blockIdx.x * blockDim.x + threadIdx.x) * 4;
    if (i + 3 < n)
    {
        float4 vda = reinterpret_cast<float4 *>(da)[i / 4];
        float4 vdb = reinterpret_cast<float4 *>(db)[i / 4];
        float4 vgo = reinterpret_cast<float4 *>(go)[i / 4];

        // No atomicAdd needed if gradients are unique to this thread!
        // We use direct addition assuming ga/gb aren't shared across indices.
        // If these are element-wise, ga[i] is only touched by thread i.
        ga[i + 0] += vdb.x * vgo.x;
        ga[i + 1] += vdb.y * vgo.y;
        ga[i + 2] += vdb.z * vgo.z;
        ga[i + 3] += vdb.w * vgo.w;

        gb[i + 0] += vda.x * vgo.x;
        gb[i + 1] += vda.y * vgo.y;
        gb[i + 2] += vda.z * vgo.z;
        gb[i + 3] += vda.w * vgo.w;
    }
    else
    {
        for (int j = i; j < n; j++)
        {
            ga[j] += db[j] * go[j];
            gb[j] += da[j] * go[j];
        }
    }
}
// ---------------------------------------------------------------------
// Numerically-safe division.
// `safe_recip(b)` returns 1/b but floors |b| at 1e-20 (sign-preserving).
// This bounds 1/b and 1/b^2 to ~1e40 instead of overflowing to +inf when
// the divisor collapses near zero. The result is still wrong in absolute
// terms when the user actually divides by zero, but it stays *finite*
// so a single rogue denominator can't poison every downstream gradient
// with NaN. Caller is still responsible for keeping denominators away
// from zero in steady state.
// ---------------------------------------------------------------------
__device__ __forceinline__ float safe_recip(float b)
{
    const float floor_abs = 1e-20f;
    float ab = fabsf(b);
    float bs = (ab < floor_abs) ? copysignf(floor_abs, b == 0.0f ? 1.0f : b) : b;
    return 1.0f / bs;
}

__global__ void div_fwd(float *a, float *b, float *out, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
        out[i] = a[i] * safe_recip(b[i]);
}
__global__ void div_bwd(float *da, float *db, float *go, float *ga, float *gb, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
    {
        float inv_b = safe_recip(db[i]);
        atomicAdd(&ga[i], go[i] * inv_b);
        atomicAdd(&gb[i], -go[i] * da[i] * inv_b * inv_b);
    }
}

// ---------------------------------------------------------------------
// pow(x, e) — NaN-free formulation.
//
// `powf(x, e)` returns NaN whenever x < 0 and e is not an exact integer.
// In a deep-learning pipeline this surfaces silently the moment any
// caller does `t.pow(0.5)` on a tensor that briefly contains negatives
// (very common: pre-activations of a residual branch, etc.).
// Likewise the backward kernel computes `e * x^(e-1) * go`, which blows
// up to +inf at x == 0 whenever e < 1 (e.g. sqrt).
//
// Strategy:
//   * If `e` rounds to a whole integer (within 1e-6), evaluate by
//     repeated multiplication. This is exact for the typical cases
//     (square, cube, x^-1 ...) and never produces NaN.
//   * Otherwise, treat the function as undefined for x <= 0 and return
//     0 (forward and backward) instead of NaN/Inf. This is the standard
//     deep-learning convention (PyTorch returns NaN, but contributors
//     typically wrap with `clamp_min`; we just bake the safe branch in).
// ---------------------------------------------------------------------
__device__ __forceinline__ float intpow(float base, int e)
{
    // Computes base^e for any signed integer e, no NaN possible.
    if (e == 0) return 1.0f;
    bool neg_exp = (e < 0);
    if (neg_exp) e = -e;
    float result = 1.0f;
    float b = base;
    while (e > 0) {
        if (e & 1) result *= b;
        b *= b;
        e >>= 1;
    }
    if (neg_exp) {
        // base^(-e) = 1 / base^e; if base==0 this is undefined -> 0.
        result = (result == 0.0f) ? 0.0f : 1.0f / result;
    }
    return result;
}

__device__ __forceinline__ bool is_integer_exp(float e, int *out_int)
{
    int rounded = __float2int_rn(e);
    if (fabsf(e - (float)rounded) < 1e-6f) {
        *out_int = rounded;
        return true;
    }
    return false;
}

__global__ void pow_fwd(float *a, float exp, float *out, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
    {
        float x = a[i];
        int ie;
        if (is_integer_exp(exp, &ie)) {
            out[i] = intpow(x, ie);
        } else {
            out[i] = (x > 0.0f) ? powf(x, exp) : 0.0f;
        }
    }
}
__global__ void pow_bwd(float *da, float exp, float *go, float *ga, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
    {
        float x = da[i];
        int ie;
        float deriv;
        if (is_integer_exp(exp, &ie)) {
            // d/dx x^ie = ie * x^(ie-1). At x==0 with ie-1 < 0 this is
            // undefined; intpow returns 0 in that case (safe).
            deriv = (float)ie * intpow(x, ie - 1);
        } else if (x > 0.0f) {
            deriv = exp * powf(x, exp - 1.0f);
        } else {
            // x <= 0 with non-integer exp: forward is defined as 0 and
            // gradient is taken to be 0 (matches the forward branch).
            return;
        }
        atomicAdd(&ga[i], deriv * go[i]);
    }
}
__global__ void relu_fwd(float *a, float *out, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
        out[i] = fmaxf(0.0f, a[i]);
}

__global__ void gelu_fwd(float *a, float *out, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
    {
        float x = a[i];
        // Standard GELU approximation
        out[i] = 0.5f * x * (1.0f + tanhf(0.7978845608f * (x + 0.044715f * x * x * x)));
    }
}

__global__ void gelu_bwd(float *a, float *go, float *ga, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
    {
        float x = a[i];
        float x3 = x * x * x;
        // Derivative of the GELU approximation
        float inner = 0.7978845608f * (x + 0.044715f * x3);
        float t = tanhf(inner);
        float sech2 = 1.0f - t * t;
        float deriv = 0.5f * (1.0f + t) + 0.5f * x * sech2 * 0.7978845608f * (1.0f + 3.0f * 0.044715f * x * x);
        atomicAdd(&ga[i], deriv * go[i]);
    }
}
__global__ void relu_bwd(float *da, float *go, float *ga, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
        atomicAdd(&ga[i], (da[i] > 0 ? 1.0f : 0.0f) * go[i]);
}
__global__ void sigmoid_fwd(float *a, float *out, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
        out[i] = 1.0f / (1.0f + expf(-a[i]));
}
__global__ void sigmoid_bwd(float *out, float *go, float *ga, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
    {
        float s = out[i];
        atomicAdd(&ga[i], s * (1.0f - s) * go[i]);
    }
}
__global__ void tanh_fwd(float *a, float *out, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
        out[i] = tanhf(a[i]);
}
__global__ void tanh_bwd(float *out, float *go, float *ga, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
    {
        float t = out[i];
        atomicAdd(&ga[i], (1.0f - t * t) * go[i]);
    }
}
__global__ void log_fwd(float *a, float *out, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
    {
        // Epsilon prevents log(0)
        out[i] = logf(a[i] + 1e-7f);
    }
}

__global__ void log_bwd(float *a, float *go, float *ga, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
    {
        // Derivative of log(x) is 1/x
        atomicAdd(&ga[i], (1.0f / (a[i] + 1e-7f)) * go[i]);
    }
}

__global__ void abs_fwd(float *a, float *out, int size)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < size)
        out[i] = fabsf(a[i]);
}

__global__ void abs_bwd(float *a, float *grad_out, float *grad_a, int size)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < size)
    {
        float val = a[i];
        float sign = (val > 0.0f) ? 1.0f : ((val < 0.0f) ? -1.0f : 0.0f);
        atomicAdd(&grad_a[i], grad_out[i] * sign);
    }
}

