// Auto-generated by tools/split_engine.py from engine.cu.
// Edit this file directly; engine.cu just #includes us.

#pragma once


__global__ void add_fwd(float *a, float *b, float *out, int n)
{
    int i = (blockIdx.x * blockDim.x + threadIdx.x) * 4;
    if (i + 3 < n)
    {
        float4 va = reinterpret_cast<float4 *>(a)[i / 4];
        float4 vb = reinterpret_cast<float4 *>(b)[i / 4];
        float4 vout;
        vout.x = va.x + vb.x;
        vout.y = va.y + vb.y;
        vout.z = va.z + vb.z;
        vout.w = va.w + vb.w;
        reinterpret_cast<float4 *>(out)[i / 4] = vout;
    }
    else
    {
        // Handle remainder
        for (int j = i; j < n; j++)
        {
            out[j] = a[j] + b[j];
        }
    }
}

__global__ void add_bwd(float *go, float *ga, float *gb, int n)
{
    int i = (blockIdx.x * blockDim.x + threadIdx.x) * 4;
    if (i + 3 < n)
    {
        float4 vgo = reinterpret_cast<float4 *>(go)[i / 4];

        // Addition gradient is just passing the output gradient back.
        // Direct addition is safe here because each index is unique to this thread.
        ga[i + 0] += vgo.x;
        ga[i + 1] += vgo.y;
        ga[i + 2] += vgo.z;
        ga[i + 3] += vgo.w;

        gb[i + 0] += vgo.x;
        gb[i + 1] += vgo.y;
        gb[i + 2] += vgo.z;
        gb[i + 3] += vgo.w;
    }
    else
    {
        for (int j = i; j < n; j++)
        {
            ga[j] += go[j];
            gb[j] += go[j];
        }
    }
}
__global__ void sub_fwd(float *a, float *b, float *out, int n)
{
    // Each thread handles 4 elements
    int i = (blockIdx.x * blockDim.x + threadIdx.x) * 4;

    if (i + 3 < n)
    {
        float4 va = reinterpret_cast<float4 *>(a + i)[0];
        float4 vb = reinterpret_cast<float4 *>(b + i)[0];
        float4 res;
        res.x = va.x - vb.x;
        res.y = va.y - vb.y;
        res.z = va.z - vb.z;
        res.w = va.w - vb.w;
        reinterpret_cast<float4 *>(out + i)[0] = res;
    }
    else
    {
        // Handle remainder elements
        for (int j = i; j < n; j++)
        {
            out[j] = a[j] - b[j];
        }
    }
}

__global__ void sub_bwd(float *go, float *ga, float *gb, int n)
{
    int i = (blockIdx.x * blockDim.x + threadIdx.x) * 4;

    if (i + 3 < n)
    {
        float4 vgo = reinterpret_cast<float4 *>(go + i)[0];

        // Note: We use atomicAdd because a tensor might be used
        // in multiple operations (aliasing), requiring gradient accumulation.
        atomicAdd(&ga[i + 0], vgo.x);
        atomicAdd(&ga[i + 1], vgo.y);
        atomicAdd(&ga[i + 2], vgo.z);
        atomicAdd(&ga[i + 3], vgo.w);

        atomicAdd(&gb[i + 0], -vgo.x);
        atomicAdd(&gb[i + 1], -vgo.y);
        atomicAdd(&gb[i + 2], -vgo.z);
        atomicAdd(&gb[i + 3], -vgo.w);
    }
    else
    {
        for (int j = i; j < n; j++)
        {
            atomicAdd(&ga[j], go[j]);
            atomicAdd(&gb[j], -go[j]);
        }
    }
}
__global__ void mul_fwd(float *a, float *b, float *out, int n)
{
    int i = (blockIdx.x * blockDim.x + threadIdx.x) * 4;
    if (i + 3 < n)
    {
        // Vectorized load and store
        float4 va = reinterpret_cast<float4 *>(a)[i / 4];
        float4 vb = reinterpret_cast<float4 *>(b)[i / 4];
        float4 vout;
        vout.x = va.x * vb.x;
        vout.y = va.y * vb.y;
        vout.z = va.z * vb.z;
        vout.w = va.w * vb.w;
        reinterpret_cast<float4 *>(out)[i / 4] = vout;
    }
    else
    {
        // Handle remainder for non-multiple of 4
        for (int j = i; j < n; j++)
        {
            out[j] = a[j] * b[j];
        }
    }
}

__global__ void mul_bwd(float *da, float *db, float *go, float *ga, float *gb, int n)
{
    int i = (blockIdx.x * blockDim.x + threadIdx.x) * 4;
    if (i + 3 < n)
    {
        float4 vda = reinterpret_cast<float4 *>(da)[i / 4];
        float4 vdb = reinterpret_cast<float4 *>(db)[i / 4];
        float4 vgo = reinterpret_cast<float4 *>(go)[i / 4];

        // No atomicAdd needed if gradients are unique to this thread!
        // We use direct addition assuming ga/gb aren't shared across indices.
        // If these are element-wise, ga[i] is only touched by thread i.
        ga[i + 0] += vdb.x * vgo.x;
        ga[i + 1] += vdb.y * vgo.y;
        ga[i + 2] += vdb.z * vgo.z;
        ga[i + 3] += vdb.w * vgo.w;

        gb[i + 0] += vda.x * vgo.x;
        gb[i + 1] += vda.y * vgo.y;
        gb[i + 2] += vda.z * vgo.z;
        gb[i + 3] += vda.w * vgo.w;
    }
    else
    {
        for (int j = i; j < n; j++)
        {
            ga[j] += db[j] * go[j];
            gb[j] += da[j] * go[j];
        }
    }
}
__global__ void div_fwd(float *a, float *b, float *out, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
        out[i] = a[i] / b[i];
}
__global__ void div_bwd(float *da, float *db, float *go, float *ga, float *gb, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
    {
        atomicAdd(&ga[i], go[i] / db[i]);
        atomicAdd(&gb[i], -go[i] * da[i] / (db[i] * db[i]));
    }
}
__global__ void pow_fwd(float *a, float exp, float *out, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
        out[i] = powf(a[i], exp);
}
__global__ void pow_bwd(float *da, float exp, float *go, float *ga, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
        atomicAdd(&ga[i], exp * powf(da[i], exp - 1.0f) * go[i]);
}
__global__ void relu_fwd(float *a, float *out, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
        out[i] = fmaxf(0.0f, a[i]);
}

__global__ void gelu_fwd(float *a, float *out, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
    {
        float x = a[i];
        // Standard GELU approximation
        out[i] = 0.5f * x * (1.0f + tanhf(0.7978845608f * (x + 0.044715f * x * x * x)));
    }
}

__global__ void gelu_bwd(float *a, float *go, float *ga, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
    {
        float x = a[i];
        float x3 = x * x * x;
        // Derivative of the GELU approximation
        float inner = 0.7978845608f * (x + 0.044715f * x3);
        float t = tanhf(inner);
        float sech2 = 1.0f - t * t;
        float deriv = 0.5f * (1.0f + t) + 0.5f * x * sech2 * 0.7978845608f * (1.0f + 3.0f * 0.044715f * x * x);
        atomicAdd(&ga[i], deriv * go[i]);
    }
}
__global__ void relu_bwd(float *da, float *go, float *ga, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
        atomicAdd(&ga[i], (da[i] > 0 ? 1.0f : 0.0f) * go[i]);
}
__global__ void sigmoid_fwd(float *a, float *out, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
        out[i] = 1.0f / (1.0f + expf(-a[i]));
}
__global__ void sigmoid_bwd(float *out, float *go, float *ga, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
    {
        float s = out[i];
        atomicAdd(&ga[i], s * (1.0f - s) * go[i]);
    }
}
__global__ void tanh_fwd(float *a, float *out, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
        out[i] = tanhf(a[i]);
}
__global__ void tanh_bwd(float *out, float *go, float *ga, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
    {
        float t = out[i];
        atomicAdd(&ga[i], (1.0f - t * t) * go[i]);
    }
}
__global__ void log_fwd(float *a, float *out, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
    {
        // Epsilon prevents log(0)
        out[i] = logf(a[i] + 1e-7f);
    }
}

__global__ void log_bwd(float *a, float *go, float *ga, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
    {
        // Derivative of log(x) is 1/x
        atomicAdd(&ga[i], (1.0f / (a[i] + 1e-7f)) * go[i]);
    }
}

__global__ void abs_fwd(float *a, float *out, int size)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < size)
        out[i] = fabsf(a[i]);
}

__global__ void abs_bwd(float *a, float *grad_out, float *grad_a, int size)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < size)
    {
        float val = a[i];
        float sign = (val > 0.0f) ? 1.0f : ((val < 0.0f) ? -1.0f : 0.0f);
        atomicAdd(&grad_a[i], grad_out[i] * sign);
    }
}

