// Auto-generated by tools/split_engine.py from engine.cu.
// Edit this file directly; engine.cu just #includes us.

#pragma once


// One-pass Welford mean/variance: numerically stable for wide rows and
// large activation magnitudes. The naive two-pass formulation
// `var = sum((x-mean)^2)/C` overflows to +inf when |x| is large enough
// that x*x exceeds FLT_MAX/C, even though the true variance fits in
// float; Welford keeps the running M2 in a normalized form that avoids
// that overflow path.
__device__ __forceinline__ void welford_row(const float *row, int C,
                                            float &mean, float &var)
{
    mean = 0.0f;
    float M2 = 0.0f;
    for (int j = 0; j < C; j++) {
        float x = row[j];
        float delta = x - mean;
        mean += delta / (float)(j + 1);
        float delta2 = x - mean;
        M2 += delta * delta2;
    }
    var = (C > 0) ? (M2 / (float)C) : 0.0f;
}

__global__ void layer_norm_fwd(float *a, float *out, int R, int C, float eps)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < R)
    {
        float mean, var;
        welford_row(a + i * C, C, mean, var);
        float inv_std = rsqrtf(var + eps);

        for (int j = 0; j < C; j++)
        {
            out[i * C + j] = (a[i * C + j] - mean) * inv_std;
        }
    }
}

__global__ void layer_norm_bwd(float *a, float *go, float *ga, int R, int C, float eps)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < R)
    {
        float mean, var;
        welford_row(a + i * C, C, mean, var);
        float inv_std = rsqrtf(var + eps);

        // 2. Compute intermediate sums for the gradient
        // dl/dx = (1/C * inv_std) * [ C*dl/dy - sum(dl/dy) - y * sum(dl/dy * y) ]
        float sum_dl_dy = 0.0f;
        float sum_dl_dy_y = 0.0f;
        for (int j = 0; j < C; j++)
        {
            float dy = go[i * C + j];
            float y = (a[i * C + j] - mean) * inv_std;
            sum_dl_dy += dy;
            sum_dl_dy_y += dy * y;
        }

        // 3. Final Gradient
        for (int j = 0; j < C; j++)
        {
            float y = (a[i * C + j] - mean) * inv_std;
            float grad = inv_std * (go[i * C + j] - (sum_dl_dy / C) - (y * sum_dl_dy_y / C));
            atomicAdd(&ga[i * C + j], grad);
        }
    }
}
__global__ void layernorm_fwd(float *x, float *gamma, float *beta, float *out, int R, int C, float eps)
{
    int i = blockIdx.x; // One row per block
    if (i < R)
    {
        float mean, var;
        welford_row(x + i * C, C, mean, var);
        float std_inv = rsqrtf(var + eps);

        // 3. Normalize and Scale/Shift
        for (int j = 0; j < C; j++)
        {
            float x_hat = (x[i * C + j] - mean) * std_inv;
            out[i * C + j] = x_hat * gamma[j] + beta[j];
        }
    }
}

__global__ void layernorm_bwd(float *x, float *gamma, float *go, float *gx, float *gGamma, float *gBeta, int R, int C, float eps)
{
    int i = blockIdx.x;
    if (i < R)
    {
        float mean, var;
        welford_row(x + i * C, C, mean, var);
        float std_inv = rsqrtf(var + eps);

        float dl_dxhat_sum = 0;
        float dl_dxhat_xhat_sum = 0;

        // First pass: Calc gradients for gamma/beta and build sums for input grad
        for (int j = 0; j < C; j++)
        {
            float x_hat = (x[i * C + j] - mean) * std_inv;
            float dl_dxhat = go[i * C + j] * gamma[j];

            dl_dxhat_sum += dl_dxhat;
            dl_dxhat_xhat_sum += dl_dxhat * x_hat;

            atomicAdd(&gGamma[j], go[i * C + j] * x_hat);
            atomicAdd(&gBeta[j], go[i * C + j]);
        }

        // Second pass: Final gradient for x
        for (int j = 0; j < C; j++)
        {
            float x_hat = (x[i * C + j] - mean) * std_inv;
            float dl_dxhat = go[i * C + j] * gamma[j];
            gx[i * C + j] += (std_inv / C) * (C * dl_dxhat - dl_dxhat_sum - x_hat * dl_dxhat_xhat_sum);
        }
    }
}

__global__ void embedding_fwd(int *indices, float *wte, float *wpe, float *out, int T, int D)
{
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx < T * D)
    {
        int t = idx / D;
        int d = idx % D;
        int token_id = indices[t];

        // Sum token embedding and position embedding
        out[idx] = wte[token_id * D + d] + wpe[t * D + d];
    }
}

// Corresponding Backward (Atomic add gradients back to embedding weights)
__global__ void embedding_bwd(int *indices, float *go, float *gwte, float *gwpe, int T, int D)
{
    int idx = blockIdx.x * blockDim.x + threadIdx.x;
    if (idx < T * D)
    {
        int t = idx / D;
        int d = idx % D;
        int token_id = indices[t];

        atomicAdd(&gwte[token_id * D + d], go[idx]);
        atomicAdd(&gwpe[t * D + d], go[idx]);
    }
}

// Fused kernel: Computes Softmax + Cross Entropy + Label Smoothing in one pass
// Each warp (32 threads) handles one row (one T)
