// Auto-generated by tools/split_engine.py from engine.cu.
// Edit this file directly; engine.cu just #includes us.

#pragma once

__global__ void cross_entropy_fwd_fast(float *logits, int *targets, float *loss, int T, int V, float epsilon)
{
    int t = blockIdx.x; // One block per row for simplicity, or use warps
    if (t >= T)
        return;

    float *row = logits + t * V;

    // 1. Find Max (Warp-wide reduction)
    float thread_max = -1e30f;
    for (int v = threadIdx.x; v < V; v += blockDim.x)
    {
        thread_max = fmaxf(thread_max, row[v]);
    }

    // Warp-level reduction
    for (int offset = 16; offset > 0; offset /= 2)
        thread_max = fmaxf(thread_max, __shfl_down_sync(0xFFFFFFFF, thread_max, offset));

    // Broadcast max to all threads in block
    __shared__ float shared_max;
    if (threadIdx.x == 0)
        shared_max = thread_max;
    __syncthreads();
    float max_val = shared_max;

    // 2. Compute Sum of Exp and Sum of Logits
    float thread_sum_exp = 0.0f;
    float thread_sum_logits = 0.0f;
    for (int v = threadIdx.x; v < V; v += blockDim.x)
    {
        float val = row[v];
        thread_sum_exp += expf(val - max_val);
        thread_sum_logits += val;
    }

    // Block-wide reduction for sums
    for (int offset = 16; offset > 0; offset /= 2)
    {
        thread_sum_exp += __shfl_down_sync(0xFFFFFFFF, thread_sum_exp, offset);
        thread_sum_logits += __shfl_down_sync(0xFFFFFFFF, thread_sum_logits, offset);
    }

    __shared__ float shared_sum_exp, shared_sum_logits;
    if (threadIdx.x == 0)
    {
        shared_sum_exp = thread_sum_exp;
        shared_sum_logits = thread_sum_logits;
    }
    __syncthreads();

    // 3. Final calculation (Thread 0 only)
    if (threadIdx.x == 0)
    {
        float lse = max_val + logf(shared_sum_exp + 1e-12f);
        float logit_target = row[targets[t]];

        float ce_loss = lse - logit_target;
        float smooth_loss = lse - (shared_sum_logits / V);
        loss[t] = (1.0f - epsilon) * ce_loss + epsilon * smooth_loss;
    }
}

// Optimized Backward: Computes (Softmax - Target) / T efficiently
__global__ void cross_entropy_bwd_fast(float *logits, int *targets, float *grad_logits, int T, int V, float grad_output, float epsilon)
{
    int t = blockIdx.x;
    if (t >= T)
        return;

    float *row_logits = logits + t * V;
    float *row_grads = grad_logits + t * V;
    int target_idx = targets[t];

    // Recompute LSE for softmax (standard practice to avoid storing large activation maps)
    float thread_max = -1e30f;
    for (int v = threadIdx.x; v < V; v += blockDim.x)
        thread_max = fmaxf(thread_max, row_logits[v]);
    for (int offset = 16; offset > 0; offset /= 2)
        thread_max = fmaxf(thread_max, __shfl_down_sync(0xFFFFFFFF, thread_max, offset));
    __shared__ float max_val;
    if (threadIdx.x == 0)
        max_val = thread_max;
    __syncthreads();

    float thread_sum_exp = 0.0f;
    for (int v = threadIdx.x; v < V; v += blockDim.x)
        thread_sum_exp += expf(row_logits[v] - max_val);
    for (int offset = 16; offset > 0; offset /= 2)
        thread_sum_exp += __shfl_down_sync(0xFFFFFFFF, thread_sum_exp, offset);
    __shared__ float sum_exp;
    if (threadIdx.x == 0)
        sum_exp = thread_sum_exp;
    __syncthreads();

    // Compute gradients for the row
    float norm = 1.0f / (sum_exp + 1e-12f);
    float scale = grad_output / (float)T;
    float eps_v = epsilon / (float)V;

    for (int v = threadIdx.x; v < V; v += blockDim.x)
    {
        float softmax = expf(row_logits[v] - max_val) * norm;
        float indicator = (v == target_idx) ? 1.0f : 0.0f;
        float target_prob = (1.0f - epsilon) * indicator + eps_v;

        row_grads[v] = (softmax - target_prob) * scale;
    }
}

// Helper for block-level reduction
__device__ float blockReduceMax(float val)
{
    static __shared__ float shared[32];
    int lane = threadIdx.x % 32;
    int wid = threadIdx.x / 32;

    // Warp reduction
    for (int offset = 16; offset > 0; offset /= 2)
        val = fmaxf(val, __shfl_down_sync(0xffffffff, val, offset));

    if (lane == 0)
        shared[wid] = val;
    __syncthreads();

    // Final warp reduction
    val = (threadIdx.x < blockDim.x / 32.0f) ? shared[lane] : -1e30f;
    if (wid == 0)
    {
        for (int offset = 16; offset > 0; offset /= 2)
            val = fmaxf(val, __shfl_down_sync(0xffffffff, val, offset));
    }
    return val;
}

__device__ float blockReduceSum(float val)
{
    static __shared__ float shared[32];
    int lane = threadIdx.x % 32;
    int wid = threadIdx.x / 32;

    for (int offset = 16; offset > 0; offset /= 2)
        val += __shfl_down_sync(0xffffffff, val, offset);

    if (lane == 0)
        shared[wid] = val;
    __syncthreads();

    val = (threadIdx.x < blockDim.x / 32.0f) ? shared[lane] : 0.0f;
    if (wid == 0)
    {
        for (int offset = 16; offset > 0; offset /= 2)
            val += __shfl_down_sync(0xffffffff, val, offset);
    }
    return val;
}

__global__ void cross_entropy_fwd_hyper(float *logits, int *targets, float *loss, int T, int V, float epsilon)
{
    int t = blockIdx.x;
    if (t >= T)
        return;

    float *row = logits + t * V;

    // 1. Max for stability
    float local_max = -1e30f;
    for (int v = threadIdx.x; v < V; v += blockDim.x)
    {
        local_max = fmaxf(local_max, row[v]);
    }
    float max_val = blockReduceMax(local_max);
    __shared__ float b_max;
    if (threadIdx.x == 0)
        b_max = max_val;
    __syncthreads();

    // 2. Sums
    float local_sum_exp = 0.0f;
    float local_sum_logits = 0.0f;
    for (int v = threadIdx.x; v < V; v += blockDim.x)
    {
        float p = expf(row[v] - b_max);
        local_sum_exp += p;
        local_sum_logits += row[v];
    }

    float total_sum_exp = blockReduceSum(local_sum_exp);
    float total_sum_logits = blockReduceSum(local_sum_logits);

    if (threadIdx.x == 0)
    {
        float lse = b_max + logf(total_sum_exp + 1e-12f);
        float logit_target = row[targets[t]];

        float ce_loss = lse - logit_target;
        float smooth_loss = lse - (total_sum_logits / V);
        loss[t] = (1.0f - epsilon) * ce_loss + epsilon * smooth_loss;
    }
}

__global__ void cross_entropy_bwd_hyper(float *logits, int *targets, float *grad_logits, int T, int V, float grad_output, float epsilon)
{
    int t = blockIdx.x;
    if (t >= T)
        return;

    float *row_logits = logits + t * V;
    float *row_grads = grad_logits + t * V;
    int target_idx = targets[t];

    // Re-calculate max and sum_exp for softmax
    float local_max = -1e30f;
    for (int v = threadIdx.x; v < V; v += blockDim.x)
        local_max = fmaxf(local_max, row_logits[v]);
    float max_val = blockReduceMax(local_max);
    __shared__ float b_max;
    if (threadIdx.x == 0)
        b_max = max_val;
    __syncthreads();

    float local_sum_exp = 0.0f;
    for (int v = threadIdx.x; v < V; v += blockDim.x)
        local_sum_exp += expf(row_logits[v] - b_max);
    float total_sum_exp = blockReduceSum(local_sum_exp);
    __shared__ float b_sum_exp;
    if (threadIdx.x == 0)
        b_sum_exp = total_sum_exp + 1e-12f;
    __syncthreads();

    float scale = grad_output / (float)T;
    for (int v = threadIdx.x; v < V; v += blockDim.x)
    {
        float softmax = expf(row_logits[v] - b_max) / b_sum_exp;
        float indicator = (v == target_idx) ? 1.0f : 0.0f;
        float target_prob = (1.0f - epsilon) * indicator + (epsilon / (float)V);
        row_grads[v] = (softmax - target_prob) * scale;
    }
}

// Simple Mean Kernel to avoid Host-Device roundtrip
__global__ void mean_kernel(float *loss, float *out, int T)
{
    float sum = 0;
    for (int i = 0; i < T; i++)
        sum += loss[i];
    *out = sum / T;
}

__global__ void adam_kernel(float *p, float *g, float *m, float *v,
                            int size, int t, float lr,
                            float b1, float b2, float eps)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < size)
    {
        // 1. Safe Step Count
        // If t is 0, powf(b1, 0) is 1, leading to 1-1=0 denominator.
        // We force t to be at least 1 for the math.
        float step = (float)t + 1.0f;

        // 2. Gradient + Weight Decay
        float weight_decay = 0.001f;
        float grad = g[i];

        // 3. Update biased moments
        m[i] = b1 * m[i] + (1.0f - b1) * grad;
        v[i] = b2 * v[i] + (1.0f - b2) * (grad * grad);

        // 4. Bias correction (Mathematically safe now)
        float m_hat = m[i] / (1.0f - powf(b1, step));
        float v_hat = v[i] / (1.0f - powf(b2, step));

        // 5. Compute Update
        float delta = lr * m_hat / (sqrtf(v_hat) + eps);

        // 6. Apply Update + Weight Decay (AdamW style)
        // This is more stable than adding decay to the gradient directly
        float new_p = p[i] - delta - (lr * weight_decay * p[i]);

        // 7. Safety Clipping
        // if (new_p > 10.0f)
        //     new_p = 10.0f;
        // if (new_p < -10.0f)
        //     new_p = -10.0f;

        p[i] = new_p;

        // --- Optional Debug ---
        // if (i == 0 && t % 100 == 0)
        //     printf("Step %d | p: %f | g: %f\n", t, p[i], g[i]);
    }
}

__global__ void sdg_kernel(float *p, float *g,
                           int size, float lr)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < size)
    {
        // 1. Safe Step Count
        // If t is 0, powf(b1, 0) is 1, leading to 1-1=0 denominator.
        // We force t to be at least 1 for the math.
        // float step = (float)t + 1.0f;

        // 2. Gradient + Weight Decay
        // float weight_decay = 0.001f;
        float grad = g[i];

        // 3. Update biased moments
        // m[i] = b1 * m[i] + (1.0f - b1) * grad;
        // v[i] = b2 * v[i] + (1.0f - b2) * (grad * grad);

        // 4. Bias correction (Mathematically safe now)
        // float m_hat = m[i] / (1.0f - powf(b1, step));
        // float v_hat = v[i] / (1.0f - powf(b2, step));

        // 5. Compute Update
        float delta = lr * grad;

        // 6. Apply Update + Weight Decay (AdamW style)
        // This is more stable than adding decay to the gradient directly
        float new_p = p[i] - delta - (lr * p[i]);

        // 7. Safety Clipping
        // if (new_p > 10.0f)
        //     new_p = 10.0f;
        // if (new_p < -10.0f)
        //     new_p = -10.0f;

        p[i] = new_p;

        // --- Optional Debug ---
        // if (i == 0 && t % 100 == 0)
        //     printf("Step %d | p: %f | g: %f\n", t, p[i], g[i]);
    }
}

__global__ void clip_grads_kernel(float *grad, float limit, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
    {
        // Clamp the gradient value between [-limit, limit]
        float g = grad[i];
        if (g > limit)
            grad[i] = limit;
        else if (g < -limit)
            grad[i] = -limit;
    }
}

