// Auto-generated by tools/split_engine.py from engine.cu.
// Edit this file directly; engine.cu just #includes us.

#pragma once

__global__ void step_kernel(float *data, float *grad, float lr, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
    {
        data[i] -= lr * grad[i];
        grad[i] = 0;
    }
}
// __global__ void matmul_fwd(float *A, float *B, float *C, int M, int K, int N)
// {
//     int row = blockIdx.y * blockDim.y + threadIdx.y;
//     int col = blockIdx.x * blockDim.x + threadIdx.x;
//     if (row < M && col < N)
//     {
//         float sum = 0;
//         for (int i = 0; i < K; i++)
//             sum += A[row * K + i] * B[i * N + col];
//         C[row * N + col] = sum;
//     }
// }
__global__ void matmul_fwd(float *A, float *B, float *C, int M, int K, int N)
{
    __shared__ float sA[32][32];
    __shared__ float sB[32][32];

    int row = blockIdx.y * 32 + threadIdx.y;
    int col = blockIdx.x * 32 + threadIdx.x;
    float sum = 0.0f;

    for (int tile = 0; tile < (K + 31) / 32; ++tile)
    {
        // Load tiles into shared memory
        if (row < M && (tile * 32 + threadIdx.x) < K)
            sA[threadIdx.y][threadIdx.x] = A[row * K + tile * 32 + threadIdx.x];
        else
            sA[threadIdx.y][threadIdx.x] = 0.0f;

        if (col < N && (tile * 32 + threadIdx.y) < K)
            sB[threadIdx.y][threadIdx.x] = B[(tile * 32 + threadIdx.y) * N + col];
        else
            sB[threadIdx.y][threadIdx.x] = 0.0f;

        __syncthreads();

        // Compute partial dot product
        for (int i = 0; i < 32; ++i)
        {
            sum += sA[threadIdx.y][i] * sB[i][threadIdx.x];
        }
        __syncthreads();
    }

    if (row < M && col < N)
    {
        C[row * N + col] = sum;
    }
}
// dA = dO * B^T
__global__ void matmul_bwd_dA_tiled(float *dO, float *B, float *dA, int M, int K, int N)
{
    __shared__ float sdO[32][32];
    __shared__ float sB[32][32];

    int row = blockIdx.y * 32 + threadIdx.y;
    int col = blockIdx.x * 32 + threadIdx.x;
    float sum = 0.0f;

    for (int tile = 0; tile < (N + 31) / 32; ++tile)
    {
        // Load dO tile
        if (row < M && (tile * 32 + threadIdx.x) < N)
            sdO[threadIdx.y][threadIdx.x] = dO[row * N + tile * 32 + threadIdx.x];
        else
            sdO[threadIdx.y][threadIdx.x] = 0.0f;

        // Load B tile (Transposed access for B^T logic)
        // B is (K x N), we want B^T which is (N x K)
        if (col < K && (tile * 32 + threadIdx.y) < N)
            sB[threadIdx.y][threadIdx.x] = B[col * N + tile * 32 + threadIdx.y];
        else
            sB[threadIdx.y][threadIdx.x] = 0.0f;

        __syncthreads();
        for (int i = 0; i < 32; ++i)
            sum += sdO[threadIdx.y][i] * sB[i][threadIdx.x];
        __syncthreads();
    }

    if (row < M && col < K)
        dA[row * K + col] += sum;
}

// dB = A^T * dO
__global__ void matmul_bwd_dB_tiled(float *A, float *dO, float *dB, int M, int K, int N)
{
    __shared__ float sA[32][32];
    __shared__ float sdO[32][32];

    int row = blockIdx.y * 32 + threadIdx.y; // K dimension
    int col = blockIdx.x * 32 + threadIdx.x; // N dimension
    float sum = 0.0f;

    for (int tile = 0; tile < (M + 31) / 32; ++tile)
    {
        // Load A tile (Transposed access for A^T logic)
        if (row < K && (tile * 32 + threadIdx.x) < M)
            sA[threadIdx.y][threadIdx.x] = A[(tile * 32 + threadIdx.x) * K + row];
        else
            sA[threadIdx.y][threadIdx.x] = 0.0f;

        // Load dO tile
        if (col < N && (tile * 32 + threadIdx.y) < M)
            sdO[threadIdx.y][threadIdx.x] = dO[(tile * 32 + threadIdx.y) * N + col];
        else
            sdO[threadIdx.y][threadIdx.x] = 0.0f;

        __syncthreads();
        for (int i = 0; i < 32; ++i)
            sum += sA[threadIdx.y][i] * sdO[i][threadIdx.x];
        __syncthreads();
    }

    if (row < K && col < N)
        dB[row * N + col] += sum;
}

// We keep the signature to avoid breaking callers, but we use cuBLAS inside
// Note: Usually, you'd pass a handle, but here we assume a global cublas_handle
// void matmul_fwd_fast(float *A, float *B, float *C, int M, int K, int N) {
//     const float alpha = 1.0f;
//     const float beta = 0.0f;
//     // Row-major C = A * B  =>  Column-major C^T = B^T * A^T
//     // A is M x K, B is K x N, C is M x N
//     cublasSgemm(cublas_handle,
//                 CUBLAS_OP_N, CUBLAS_OP_N,
//                 N, M, K,
//                 &alpha, B, N, A, K, &beta, C, N);
// }

__global__ void sum_fwd_kernel(float *a, float *out, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
    {
        // Atomically add each element to the first slot of the output
        atomicAdd(out, a[i]);
    }
}

__global__ void sum_bwd_kernel(float *grad_out, float *grad_a, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
    {
        // The gradient of a sum is 1.0.
        // We multiply the incoming gradient (grad_out[0]) by 1.0 and pass it back.
        atomicAdd(&grad_a[i], grad_out[0]);
    }
}

__global__ void mean_fwd_kernel(float *a, float *out, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
    {
        // Add (value / n) to the output to get the mean
        atomicAdd(out, a[i] / (float)n);
    }
}

__global__ void mean_bwd_kernel(float *grad_out, float *grad_a, int n)
{
    int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i < n)
    {
        // The gradient of mean(x) is 1/n.
        atomicAdd(&grad_a[i], grad_out[0] / (float)n);
    }
}

