name: dart_cuda
description: A high-performance Dart & CUDA Deep Learning engine with Autograd and AFT support.
version: 1.0.0
repository: https://github.com/KellyKinyama/dart_cuda
topics: [machine-learning, cuda, gpu, ai]

environment:
  sdk: ^3.9.3

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  ffi: ^2.1.4
  bishop: ^1.4.4
  test: ^1.29.0
  image: ^4.8.0

dev_dependencies:
  lints: ^6.0.0
