#!/usr/bin/env python3
"""Split native/src/engine.cu into kernel header fragments + thin engine.cu.

Preserves single-TU compilation: engine.cu still compiled by `nvcc engine.cu`.
Idempotent: writes new files in `native/src/kernels/` and overwrites engine.cu.
"""
from pathlib import Path

ROOT = Path("/mnt/c/Users/kkinyama/dart_cuda/native/src")
SRC = ROOT / "engine.cu"
KERNELS = ROOT / "kernels"
KERNELS.mkdir(exist_ok=True)

src_lines = SRC.read_text().splitlines(keepends=True)
# 1-indexed, inclusive ranges. Verified against `grep -nE __global__` output.
GROUPS = {
    "common": [(1, 62)],
    "layernorm_embed": [(63, 131), (748, 822), (823, 853)],
    "elementwise": [
        (132, 310),    # add/sub/mul/div fwd+bwd
        (311, 322),    # pow
        (323, 391),    # relu/gelu/sigmoid/tanh
        (532, 551),    # log
        (1225, 1242),  # abs
    ],
    "matmul": [
        (392, 412),    # step_kernel
        (413, 531),    # matmul
        (1266, 1306),  # sum/mean fwd+bwd
    ],
    "attention": [
        (552, 674),    # aft_full + aft_cross
        (675, 747),    # concat axis0+axis1
    ],
    "loss_optim": [
        (854, 1102),   # cross_entropy + mean_kernel
        (1103, 1205),  # adam + sdg + clip
    ],
    "conv_misc": [
        (1206, 1224),  # slice
        (1243, 1265),  # compute_cost_matrix
        (1307, 1321),  # xavier_init
        (1322, 1408),  # im2col + col2im
    ],
}
EXTERN_C_START = 1409  # First line of `extern "C" {` block

# Sanity: every line 1..EXTERN_C_START-1 must be covered exactly once.
covered = [False] * (EXTERN_C_START)
for grp, ranges in GROUPS.items():
    for a, b in ranges:
        for i in range(a, b + 1):
            assert not covered[i], f"line {i} in two groups (last: {grp})"
            covered[i] = True
for i in range(1, EXTERN_C_START):
    assert covered[i], f"line {i} uncovered"

def slice_lines(ranges):
    out = []
    for a, b in ranges:
        out.extend(src_lines[a - 1 : b])
    return out

# Header for each .cuh fragment.
HEADER_TMPL = (
    "// Auto-generated by tools/split_engine.py from engine.cu.\n"
    "// Edit this file directly; engine.cu just #includes us.\n\n"
    "#pragma once\n\n"
)

# common.cuh contains the global #include block + macros — no #pragma once shim
# is needed but it doesn't hurt. We strip the existing pragma-style comment.
for name in ["common", "elementwise", "matmul", "attention",
            "layernorm_embed", "loss_optim", "conv_misc"]:
    body = "".join(slice_lines(GROUPS[name]))
    out = HEADER_TMPL + body
    (KERNELS / f"{name}.cuh").write_text(out)

# Reconstruct engine.cu: shim header + includes + extern "C" body.
extern_body = "".join(src_lines[EXTERN_C_START - 1 :])
new_engine = (
    "// engine.cu — thin entry point.\n"
    "//\n"
    "// CUDA kernels live in `kernels/*.cuh` (single translation unit via\n"
    "// #include); only the `extern \"C\"` DLLEXPORT wrappers stay here.\n"
    "// Build: `nvcc --shared -o native/lib/libmat_mul.so native/src/engine.cu`.\n\n"
    '#include "kernels/common.cuh"\n'
    '#include "kernels/elementwise.cuh"\n'
    '#include "kernels/matmul.cuh"\n'
    '#include "kernels/attention.cuh"\n'
    '#include "kernels/layernorm_embed.cuh"\n'
    '#include "kernels/loss_optim.cuh"\n'
    '#include "kernels/conv_misc.cuh"\n\n'
) + extern_body

SRC.write_text(new_engine)
print("engine.cu lines:", new_engine.count("\n"))
for f in sorted(KERNELS.glob("*.cuh")):
    print(f.name, ":", f.read_text().count("\n"), "lines")
